
package mx.gob.imss.cit.bp.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocumentoWSServiceImplService", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/")
public class DocumentoWSServiceImplService
    extends Service
{

    private final static URL DOCUMENTOWSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.gob.imss.cit.bp.ws.DocumentoWSServiceImplService.class.getName());
    
    static {
    	URL url = null;
    	URL baseUrl = null;
    	StringBuilder sb = null;
    	String ip = null;
    	String port = null;
    	String context = null;
		try {
			ip = "localhost";
			port = "8080";
			context = "/boveda-personal-escritorio-ws/DocumentoWSServiceImplService";
			if( ip != null && context != null){
				sb = new StringBuilder( "http://" );
				sb.append( ip );
				if( port != null && !port.isEmpty()){
					sb.append(":");
					sb.append(port);
				}
				sb.append( context );
			}
				baseUrl = mx.gob.imss.cit.bp.ws.DocumentoWSServiceImplService.class.getResource(".");
				url = new URL(baseUrl, sb.toString() );
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl, retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTOWSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

//    public DocumentoWSServiceImplService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }

    public DocumentoWSServiceImplService() {
        super(DOCUMENTOWSSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://documentows.ws.bp.cit.imss.gob.mx/", "DocumentoWSServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns DocumentoWSServiceImpl
     */
    @WebEndpoint(name = "DocumentoWSServiceImplPort")
    public DocumentoWSServiceImpl getDocumentoWSServiceImplPort() {
        return super.getPort(new QName("http://documentows.ws.bp.cit.imss.gob.mx/", "DocumentoWSServiceImplPort"), DocumentoWSServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentoWSServiceImpl
     */
    @WebEndpoint(name = "DocumentoWSServiceImplPort")
    public DocumentoWSServiceImpl getDocumentoWSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://documentows.ws.bp.cit.imss.gob.mx/", "DocumentoWSServiceImplPort"), DocumentoWSServiceImpl.class, features);
    }

}
