
package mx.gob.imss.cit.bp.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mx.gob.imss.cit.bp.ws.AddDocumentActorRequest;
import mx.gob.imss.cit.bp.ws.AddDocumentActorResponse;
import mx.gob.imss.cit.bp.ws.AllDocumentVersionsByDocRequest;
import mx.gob.imss.cit.bp.ws.AllDocumentVersionsByDocResponse;
import mx.gob.imss.cit.bp.ws.AllDocumentVersionsMetadataByDocRequest;
import mx.gob.imss.cit.bp.ws.AllDocumentVersionsMetadataByDocResponse;
import mx.gob.imss.cit.bp.ws.AllMetadataByMetadataRequest;
import mx.gob.imss.cit.bp.ws.AllMetadataByMetadataResponse;
import mx.gob.imss.cit.bp.ws.CreateDocumentRequest;
import mx.gob.imss.cit.bp.ws.CreateDocumentResponse;
import mx.gob.imss.cit.bp.ws.DeleteDocumentRequest;
import mx.gob.imss.cit.bp.ws.DeleteDocumentResponse;
import mx.gob.imss.cit.bp.ws.DocumentRequest;
import mx.gob.imss.cit.bp.ws.DocumentResponse;
import mx.gob.imss.cit.bp.ws.DocumentsByMetadataRequest;
import mx.gob.imss.cit.bp.ws.DocumentsByMetadataResponse;
import mx.gob.imss.cit.bp.ws.MetadataByDocRequest;
import mx.gob.imss.cit.bp.ws.MetadataByDocResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocumentoWSServiceImpl", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/")
@XmlSeeAlso({
    mx.gob.imss.cit.bp.ws.bovedapersonalcommonschema.ObjectFactory.class,
    mx.gob.imss.cit.bp.ws.ObjectFactory.class,
    mx.gob.imss.cit.bp.ws.ObjectFactory.class
})
public interface DocumentoWSServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.imss.cit.bp.ws.DocumentResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetDocument")
    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetDocumentResponse")
    public DocumentResponse getDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        DocumentRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.imss.cit.bp.ws.CreateDocumentResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDocument", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.CreateDocument")
    @ResponseWrapper(localName = "createDocumentResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.CreateDocumentResponse")
    public CreateDocumentResponse createDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        CreateDocumentRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.imss.cit.bp.ws.DeleteDocumentResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteDocument", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.DeleteDocument")
    @ResponseWrapper(localName = "deleteDocumentResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.DeleteDocumentResponse")
    public DeleteDocumentResponse deleteDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        DeleteDocumentRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.imss.cit.bp.ws.DocumentsByMetadataResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDocumentsByMetadata", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.FindDocumentsByMetadata")
    @ResponseWrapper(localName = "findDocumentsByMetadataResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.FindDocumentsByMetadataResponse")
    public DocumentsByMetadataResponse findDocumentsByMetadata(
        @WebParam(name = "arg0", targetNamespace = "")
        DocumentsByMetadataRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AllMetadataByMetadataResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllMetadataByMetadata", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetAllMetadataByMetadata")
    @ResponseWrapper(localName = "getAllMetadataByMetadataResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetAllMetadataByMetadataResponse")
    public AllMetadataByMetadataResponse getAllMetadataByMetadata(
        @WebParam(name = "arg0", targetNamespace = "")
        AllMetadataByMetadataRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.imss.cit.bp.ws.MetadataByDocResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMetadataByDoc", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetMetadataByDoc")
    @ResponseWrapper(localName = "getMetadataByDocResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetMetadataByDocResponse")
    public MetadataByDocResponse getMetadataByDoc(
        @WebParam(name = "arg0", targetNamespace = "")
        MetadataByDocRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AllDocumentVersionsByDocResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDocumentVersionsByDoc", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetAllDocumentVersionsByDoc")
    @ResponseWrapper(localName = "getAllDocumentVersionsByDocResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetAllDocumentVersionsByDocResponse")
    public AllDocumentVersionsByDocResponse getAllDocumentVersionsByDoc(
        @WebParam(name = "arg0", targetNamespace = "")
        AllDocumentVersionsByDocRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AllDocumentVersionsMetadataByDocResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDocumentVersionsMetadataByDoc", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetAllDocumentVersionsMetadataByDoc")
    @ResponseWrapper(localName = "getAllDocumentVersionsMetadataByDocResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.GetAllDocumentVersionsMetadataByDocResponse")
    public AllDocumentVersionsMetadataByDocResponse getAllDocumentVersionsMetadataByDoc(
        @WebParam(name = "arg0", targetNamespace = "")
        AllDocumentVersionsMetadataByDocRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AddDocumentActorResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addDocumentActor", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.AddDocumentActor")
    @ResponseWrapper(localName = "addDocumentActorResponse", targetNamespace = "http://documentows.ws.bp.cit.imss.gob.mx/", className = "mx.gob.imss.cit.bp.ws.documentows.AddDocumentActorResponse")
    public AddDocumentActorResponse addDocumentActor(
        @WebParam(name = "arg0", targetNamespace = "")
        AddDocumentActorRequest arg0);

}
