
package mx.gob.imss.cit.bp.ws.carpetaws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CarpetaWS", targetNamespace = "http://ws.bp.cit.imss.gob.mx/CarpetaWS", wsdlLocation = "file:/C:/Users/ysamu/Desktop/Carpeta.wsdl")
public class CarpetaWS
    extends Service
{

    private final static URL CARPETAWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.gob.imss.cit.bp.ws.carpetaws.CarpetaWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.gob.imss.cit.bp.ws.carpetaws.CarpetaWS.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/ysamu/Desktop/Carpeta.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/ysamu/Desktop/Carpeta.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CARPETAWS_WSDL_LOCATION = url;
    }

    public CarpetaWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarpetaWS() {
        super(CARPETAWS_WSDL_LOCATION, new QName("http://ws.bp.cit.imss.gob.mx/CarpetaWS", "CarpetaWS"));
    }

    /**
     * 
     * @return
     *     returns CarpetaWSService
     */
    @WebEndpoint(name = "CarpetaServiceSOAP")
    public CarpetaWSService getCarpetaServiceSOAP() {
        return super.getPort(new QName("http://ws.bp.cit.imss.gob.mx/CarpetaWS", "CarpetaServiceSOAP"), CarpetaWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarpetaWSService
     */
    @WebEndpoint(name = "CarpetaServiceSOAP")
    public CarpetaWSService getCarpetaServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.bp.cit.imss.gob.mx/CarpetaWS", "CarpetaServiceSOAP"), CarpetaWSService.class, features);
    }

}
