
package mx.gob.imss.cit.bp.ws.documentows;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import mx.gob.imss.cit.bp.ws.AddDocumentActorRequest;
import mx.gob.imss.cit.bp.ws.AddDocumentActorResponse;
import mx.gob.imss.cit.bp.ws.AllDocumentVersionsByDocRequest;
import mx.gob.imss.cit.bp.ws.AllDocumentVersionsByDocResponse;
import mx.gob.imss.cit.bp.ws.AllDocumentVersionsMetadataByDocRequest;
import mx.gob.imss.cit.bp.ws.AllDocumentVersionsMetadataByDocResponse;
import mx.gob.imss.cit.bp.ws.AllMetadataByMetadataRequest;
import mx.gob.imss.cit.bp.ws.AllMetadataByMetadataResponse;
import mx.gob.imss.cit.bp.ws.CreateDocumentRequest;
import mx.gob.imss.cit.bp.ws.CreateDocumentResponse;
import mx.gob.imss.cit.bp.ws.DeleteDocumentRequest;
import mx.gob.imss.cit.bp.ws.DeleteDocumentResponse;
import mx.gob.imss.cit.bp.ws.DocumentRequest;
import mx.gob.imss.cit.bp.ws.DocumentResponse;
import mx.gob.imss.cit.bp.ws.DocumentsByMetadataRequest;
import mx.gob.imss.cit.bp.ws.DocumentsByMetadataResponse;
import mx.gob.imss.cit.bp.ws.MetadataByDocRequest;
import mx.gob.imss.cit.bp.ws.MetadataByDocResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocumentoWSService", targetNamespace = "http://ws.bp.cit.imss.gob.mx/DocumentoWS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    mx.gob.imss.cit.bp.ws.bovedapersonalcommonschema.ObjectFactory.class,
    mx.gob.imss.cit.bp.ws.ObjectFactory.class
})
public interface IDocumentoWSService {


    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.CreateDocumentResponse
     */
    @WebMethod
    @WebResult(name = "CreateDocumentResponse", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
    public CreateDocumentResponse createDocument(
        @WebParam(name = "CreateDocumentRequest", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
        CreateDocumentRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.DeleteDocumentResponse
     */
    @WebMethod
    @WebResult(name = "DeleteDocumentResponse", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
    public DeleteDocumentResponse deleteDocument(
        @WebParam(name = "DeleteDocumentRequest", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
        DeleteDocumentRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.DocumentResponse
     */
    @WebMethod
    @WebResult(name = "DocumentResponse", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
    public DocumentResponse getDocument(
        @WebParam(name = "DocumentRequest", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
        DocumentRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.MetadataByDocResponse
     */
    @WebMethod
    @WebResult(name = "MetadataByDocResponse", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
    public MetadataByDocResponse getMetadataByDoc(
        @WebParam(name = "MetadataByDocRequest", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
        MetadataByDocRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AllDocumentVersionsByDocResponse
     */
    @WebMethod
    @WebResult(name = "AllDocumentVersionsByDocResponse", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
    public AllDocumentVersionsByDocResponse getAllDocumentVersionsByDoc(
        @WebParam(name = "AllDocumentVersionsByDocRequest", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
        AllDocumentVersionsByDocRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AllDocumentVersionsMetadataByDocResponse
     */
    @WebMethod
    @WebResult(name = "AllDocumentVersionsMetadataByDocResponse", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
    public AllDocumentVersionsMetadataByDocResponse getAllDocumentVersionsMetadataByDoc(
        @WebParam(name = "AllDocumentVersionsMetadataByDocRequest", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
        AllDocumentVersionsMetadataByDocRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.DocumentsByMetadataResponse
     */
    @WebMethod
    @WebResult(name = "DocumentsByMetadataResponse", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
    public DocumentsByMetadataResponse findDocumentsByMetadata(
        @WebParam(name = "DocumentsByMetadataRequest", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
        DocumentsByMetadataRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AllMetadataByMetadataResponse
     */
    @WebMethod
    @WebResult(name = "AllMetadataByMetadataResponse", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
    public AllMetadataByMetadataResponse getAllMetadataByMetadata(
        @WebParam(name = "AllMetadataByMetadataRequest", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
        AllMetadataByMetadataRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.cit.bp.ws.AddDocumentActorResponse
     */
    @WebMethod
    @WebResult(name = "AddDocumentActorResponse", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
    public AddDocumentActorResponse addDocumentActor(
        @WebParam(name = "AddDocumentActorRequest", targetNamespace = "http://ws.bp.cit.imss.gob.mx/", partName = "body")
        AddDocumentActorRequest body);

}
